spring:
  datasource:
    read-only:
      url: jdbc:mysql://localhost:3306/wehelp
      username: user
      password: pass
      driver-class-name: com.mysql.cj.jdbc.Driver

    write-only:
      url: jdbc:mysql://localhost:3306/wehelp
      username: user
      password: pass
      driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    datasource:
      url: jdbc:mysql://localhost:3306/wehelp
      username: user
      password: pass
      driver-class-name: com.mysql.cj.jdbc.Driver
      locations: classpath:db/migration/