services:
  mysql:
    image: 'mysql:8.4.2'
    environment:
      - 'MYSQL_DATABASE=wehelp'
      - 'MYSQL_PASSWORD=pass'
      - 'MYSQL_ROOT_PASSWORD=pass'
      - 'MYSQL_USER=user'
    ports:
      - "3306:3306"
      - "33060:33060"
